version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.11.
    steps:
      - checkout
      
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: python Utest.py


workflows:
  sample: 
    jobs:
      - build-and-test
