version: 2.1


orbs:  
  python: circleci/python@1.5.0

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.11

    steps:
      - checkout
      
      # check pip version
      - run: 
        name: upgrade-pip
        command: pip install --upgrade pip

      # install dependencies
      - run: 
        name: install-packages
        command: 
          python3 -m venv venv
          . /venv/bin/activate
          pip install -r requirements.txt

      # main tests
      - run: 
        name: Utests
        command: python Utest.py

      - save_cache:
          paths:
            - venv
          key: v1-python-cache-{{ checksum "requirements.txt" }}

workflows:
  Main:
    jobs:
      - build-and-test
